name: Dependabot auto-approve

on:
  workflow_run:
    workflows: [ Test ]
    types: 
      - completed

jobs:
  dependabot:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      run: gh pr review --approve "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
